### PR TITLE
Experiments

### PR DESCRIPTION
**Pull request by darcymason**
Various files here while trying a number of things, needs to be pruned later.

Important one is in `egsnrc/egsnrc/expts/sim1`, the `sim1.py` script and the `sim1.ipynb` notebook to run it on Colab with sim1.py stored in google drive (In Colab on left pane, click on the file folder icon, then at top on the folder icon with google drive symbol to connect google drive).

Sim1 is a "toy" photon-only simulation with very simplified geometry and iterations, but it illustrates the skeleton of a photon simulation.  It is pure Python plus Numba GPU capabilities and does the following:
- takes a 'command-line' argument of the number of histories to run.
- initializes that number of photons with energy [ 0.511 + (random # on [0, 1) ] at (0, 0, 0).
- runs a Numba GPU kernel;  each thread follows one particle until it terminates either by leaving the geometry or "photoelectric" absorption
- the geometry is two 'slabs' of 2 cm each
- on each step, a random distance of [0, 1) is moved in Z.  No angles done in this simple script.
- the interaction probabilities are a fixed percentage in each region (region zero: 80% "compton", 20% "photoelectric", region 1: 50/50).  If "Compton", then new energy is 0.8 times old energy.  If energy < 0.001, particle is cut.
- on each step, a "GPU device function" scoring function is called which tracks number and energy for the interactions and regions
- after all particles, the scoring array is copied back to CPU and various summaries printed out.  If the number of particles requested is less than 50, the entire scoring array is printed.

So far, the only testing is that the scoring results for <50 particles look reasonable given the simulation geometry and interaction probabilities.

The 'simulation' is run three times to show the jitting cost on the first run. With this simple code on Tesla T4 GPU on colab, get times 0.53, 0.046, 0.045  seconds, for 3 runs of 10 M 'particles' (times do not include initial creation of arrays and moving to the GPU).

I've tried various vectorization approaches as well using e.g. Numpy, or PyTorch for vectorizing on GPU, but I believe the kernel approach above is more promising.  Vectorized code is much harder to read, and results in a lot of array masking and copying in memory.  Kernel threads can operate at length on a small amount of data, which optimizes the use of the parallel threads.

Having said that, the approach in sim1 here is fairly naïve,  performance could likely be improved by trying to avoid as many branches in one kernel, because threads in a warp stall as they go down different paths.

Numba advantages so far:
- simple code, direct translation from Mortran original should work
- fairly well-documented, long-standing library

Disadvantages:
- limited types can be passed.  So far unable to use a ~~namedtuple~~ [Update: got namedtuple to work with a lot of forced typing] or a class to group particle information together, however these are planned for future Numba releases

### CODE REVIEW

**Comment by SimonBiggs** [comment]
I really like it! 🙂 It sounds like Numba might a very good choice in being the way to go.

**Comment by darcymason** [comment]
> I really like it! 🙂 It sounds like Numba might a very good choice in being the way to go.

👍 

And in terms of code, the Numba part is quite light - just the random numbers setup and use, and decorators on the functions.  It would be fairly easy to translate to other libraries that operate pretty similarly - Codon, CuPy, Jax, although I found Jax to be very restrictive in this context - it seems to be much more geared to vectorized code.

**Comment by SimonBiggs** [comment]
Yup, and I have since found out that JAX doesn't have a good story for installing in Windows at the moment. Also, its PyPI installation method isn't just pip install and go.

So things like that also make it quite painful as a choice.

**Comment by darcymason** [comment]
Following up on comparing vectorized vs. kernel, here is a summary of my timings on just calling a `compton` function repeatedly (translation of Mortran Compton code but no binding energies, no sampling of phi, no electron).
```
Times on Colab for Compton code:
Vectorized code, PyTorch on CPU only:  0.26 sec for 1M
Vectorized code, PyTorch on GPU     :  0.022 sec for 1M
Numba Compton kernel on GPU         :  0.011 sec for ~2.1 M, after jit (0.35 sec)  (2.097 M = 4096 blocks x 512 threads per block)
```
By comparison, _on my laptop_, the vectorized code using _Numpy_ (not Numba) was ~0.45 sec for 1M.  Pure non-vectorized Python was 24.4 sec. and compiling the Python with Numba (non-GPU) gave ~0.055 sec. for 100K, so presumably ~0.55 sec for 1M.

**Comment by darcymason** [comment]
Ignoring failing tests for now, going to pull this in and keep going on separate branch / PR.

**Pull request merged**
